/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/badge.vue')['default']
    HomeContributor: typeof import('./components/home-contributor.vue')['default']
    PackageContributor: typeof import('./components/package-contributor.vue')['default']
    PageInfo: typeof import('./components/page-info.vue')['default']
    Video: typeof import('./components/video.vue')['default']
  }
}
