/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/badge.vue')['default']
    HomeContributor: typeof import('./components/home-contributor.vue')['default']
    PackageContributor: typeof import('./components/package-contributor.vue')['default']
    PageInfo: typeof import('./components/page-info.vue')['default']
    Video: typeof import('./components/video.vue')['default']
  }
}

// For TSX support
declare global {
  const Badge: typeof import('./components/badge.vue')['default']
  const HomeContributor: typeof import('./components/home-contributor.vue')['default']
  const PackageContributor: typeof import('./components/package-contributor.vue')['default']
  const PageInfo: typeof import('./components/page-info.vue')['default']
  const Video: typeof import('./components/video.vue')['default']
}